<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class SuratMasukSeeder extends Seeder
{
    public function run()
    {
    $data = [
        [
            'jenis_agenda_tp' => 'Agenda A',
            'kode_lama' => Str::random(10),
            'kode_baru' => Str::random(10),
            'nomor_surat' => '123/ABC/2023',
            'opd_id' => 'OPD001',
            'tgl_surat' => '2023-07-01',
            'tgl_terima' => '2023-07-02',
            'acara' => 'Acara 1',
            'tanggalBerangkat' => '2023-07-03',
            'tanggalPulang' => '2023-07-04',
            'jamMulai' => '09:00:00',
            'tempat' => 'Tempat 1',
            'perihal' => 'Perihal 1',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'jenis_agenda_tp' => 'Agenda B',
            'kode_lama' => Str::random(10),
            'kode_baru' => Str::random(10),
            'nomor_surat' => '124/ABC/2023',
            'opd_id' => 'OPD002',
            'tgl_surat' => '2023-07-05',
            'tgl_terima' => '2023-07-06',
            'acara' => 'Acara 2',
            'tanggalBerangkat' => '2023-07-07',
            'tanggalPulang' => '2023-07-08',
            'jamMulai' => '10:00:00',
            'tempat' => 'Tempat 2',
            'perihal' => 'Perihal 2',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'jenis_agenda_tp' => 'Agenda C',
            'kode_lama' => Str::random(10),
            'kode_baru' => Str::random(10),
            'nomor_surat' => '125/ABC/2023',
            'opd_id' => 'OPD003',
            'tgl_surat' => '2023-07-09',
            'tgl_terima' => '2023-07-10',
            'acara' => 'Acara 3',
            'tanggalBerangkat' => '2023-07-11',
            'tanggalPulang' => '2023-07-12',
            'jamMulai' => '11:00:00',
            'tempat' => 'Tempat 3',
            'perihal' => 'Perihal 3',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'jenis_agenda_tp' => 'Agenda D',
            'kode_lama' => Str::random(10),
            'kode_baru' => Str::random(10),
            'nomor_surat' => '126/ABC/2023',
            'opd_id' => 'OPD004',
            'tgl_surat' => '2023-07-13',
            'tgl_terima' => '2023-07-14',
            'acara' => 'Acara 4',
            'tanggalBerangkat' => '2023-07-15',
            'tanggalPulang' => '2023-07-16',
            'jamMulai' => '12:00:00',
            'tempat' => 'Tempat 4',
            'perihal' => 'Perihal 4',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'jenis_agenda_tp' => 'Agenda E',
            'kode_lama' => Str::random(10),
            'kode_baru' => Str::random(10),
            'nomor_surat' => '127/ABC/2023',
            'opd_id' => 'OPD005',
            'tgl_surat' => '2023-07-17',
            'tgl_terima' => '2023-07-18',
            'acara' => 'Acara 5',
            'tanggalBerangkat' => '2023-07-19',
            'tanggalPulang' => '2023-07-20',
            'jamMulai' => '13:00:00',
            'tempat' => 'Tempat 5',
            'perihal' => 'Perihal 5',
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'jenis_agenda_tp' => 'Agenda A',
            'kode_lama' => Str::random(10),
            'kode_baru' => Str::random(10),
            'nomor_surat' => '123/ABC/2023',
            'opd_id' => 'OPD001',
            'tgl_surat' => '2023-07-01',
            'tgl_terima' => '2023-07-02',
            'acara' => 'Acara 1',
            'tanggalBerangkat' => '2023-07-03',
            'tanggalPulang' => '2023-07-04',
            'jamMulai' => '09:00:00',
            'tempat' => 'Tempat 1',
            'perihal' => 'Perihal 1',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'jenis_agenda_tp' => 'Agenda B',
            'kode_lama' => Str::random(10),
            'kode_baru' => Str::random(10),
            'nomor_surat' => '124/ABC/2023',
            'opd_id' => 'OPD002',
            'tgl_surat' => '2023-07-05',
            'tgl_terima' => '2023-07-06',
            'acara' => 'Acara 2',
            'tanggalBerangkat' => '2023-07-07',
            'tanggalPulang' => '2023-07-08',
            'jamMulai' => '10:00:00',
            'tempat' => 'Tempat 2',
            'perihal' => 'Perihal 2',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'jenis_agenda_tp' => 'Agenda C',
            'kode_lama' => Str::random(10),
            'kode_baru' => Str::random(10),
            'nomor_surat' => '125/ABC/2023',
            'opd_id' => 'OPD003',
            'tgl_surat' => '2023-07-09',
            'tgl_terima' => '2023-07-10',
            'acara' => 'Acara 3',
            'tanggalBerangkat' => '2023-07-11',
            'tanggalPulang' => '2023-07-12',
            'jamMulai' => '11:00:00',
            'tempat' => 'Tempat 3',
            'perihal' => 'Perihal 3',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'jenis_agenda_tp' => 'Agenda D',
            'kode_lama' => Str::random(10),
            'kode_baru' => Str::random(10),
            'nomor_surat' => '126/ABC/2023',
            'opd_id' => 'OPD004',
            'tgl_surat' => '2023-07-13',
            'tgl_terima' => '2023-07-14',
            'acara' => 'Acara 4',
            'tanggalBerangkat' => '2023-07-15',
            'tanggalPulang' => '2023-07-16',
            'jamMulai' => '12:00:00',
            'tempat' => 'Tempat 4',
            'perihal' => 'Perihal 4',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'jenis_agenda_tp' => 'Agenda E',
            'kode_lama' => Str::random(10),
            'kode_baru' => Str::random(10),
            'nomor_surat' => '127/ABC/2023',
            'opd_id' => 'OPD005',
            'tgl_surat' => '2023-07-17',
            'tgl_terima' => '2023-07-18',
            'acara' => 'Acara 5',
            'tanggalBerangkat' => '2023-07-19',
            'tanggalPulang' => '2023-07-20',
            'jamMulai' => '13:00:00',
            'tempat' => 'Tempat 5',
            'perihal' => 'Perihal 5',
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'jenis_agenda_tp' => 'Agenda A',
            'kode_lama' => Str::random(10),
            'kode_baru' => Str::random(10),
            'nomor_surat' => '123/ABC/2023',
            'opd_id' => 'OPD001',
            'tgl_surat' => '2023-07-01',
            'tgl_terima' => '2023-07-02',
            'acara' => 'Acara 1',
            'tanggalBerangkat' => '2023-07-03',
            'tanggalPulang' => '2023-07-04',
            'jamMulai' => '09:00:00',
            'tempat' => 'Tempat 1',
            'perihal' => 'Perihal 1',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'jenis_agenda_tp' => 'Agenda B',
            'kode_lama' => Str::random(10),
            'kode_baru' => Str::random(10),
            'nomor_surat' => '124/ABC/2023',
            'opd_id' => 'OPD002',
            'tgl_surat' => '2023-07-05',
            'tgl_terima' => '2023-07-06',
            'acara' => 'Acara 2',
            'tanggalBerangkat' => '2023-07-07',
            'tanggalPulang' => '2023-07-08',
            'jamMulai' => '10:00:00',
            'tempat' => 'Tempat 2',
            'perihal' => 'Perihal 2',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'jenis_agenda_tp' => 'Agenda C',
            'kode_lama' => Str::random(10),
            'kode_baru' => Str::random(10),
            'nomor_surat' => '125/ABC/2023',
            'opd_id' => 'OPD003',
            'tgl_surat' => '2023-07-09',
            'tgl_terima' => '2023-07-10',
            'acara' => 'Acara 3',
            'tanggalBerangkat' => '2023-07-11',
            'tanggalPulang' => '2023-07-12',
            'jamMulai' => '11:00:00',
            'tempat' => 'Tempat 3',
            'perihal' => 'Perihal 3',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'jenis_agenda_tp' => 'Agenda D',
            'kode_lama' => Str::random(10),
            'kode_baru' => Str::random(10),
            'nomor_surat' => '126/ABC/2023',
            'opd_id' => 'OPD004',
            'tgl_surat' => '2023-07-13',
            'tgl_terima' => '2023-07-14',
            'acara' => 'Acara 4',
            'tanggalBerangkat' => '2023-07-15',
            'tanggalPulang' => '2023-07-16',
            'jamMulai' => '12:00:00',
            'tempat' => 'Tempat 4',
            'perihal' => 'Perihal 4',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'jenis_agenda_tp' => 'Agenda E',
            'kode_lama' => Str::random(10),
            'kode_baru' => Str::random(10),
            'nomor_surat' => '127/ABC/2023',
            'opd_id' => 'OPD005',
            'tgl_surat' => '2023-07-17',
            'tgl_terima' => '2023-07-18',
            'acara' => 'Acara 5',
            'tanggalBerangkat' => '2023-07-19',
            'tanggalPulang' => '2023-07-20',
            'jamMulai' => '13:00:00',
            'tempat' => 'Tempat 5',
            'perihal' => 'Perihal 5',
            'created_at' => now(),
            'updated_at' => now(),
        ],


        [
            'jenis_agenda_tp' => 'Agenda A',
            'kode_lama' => Str::random(10),
            'kode_baru' => Str::random(10),
            'nomor_surat' => '123/ABC/2023',
            'opd_id' => 'OPD001',
            'tgl_surat' => '2023-07-01',
            'tgl_terima' => '2023-07-02',
            'acara' => 'Acara 1',
            'tanggalBerangkat' => '2023-07-03',
            'tanggalPulang' => '2023-07-04',
            'jamMulai' => '09:00:00',
            'tempat' => 'Tempat 1',
            'perihal' => 'Perihal 1',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'jenis_agenda_tp' => 'Agenda B',
            'kode_lama' => Str::random(10),
            'kode_baru' => Str::random(10),
            'nomor_surat' => '124/ABC/2023',
            'opd_id' => 'OPD002',
            'tgl_surat' => '2023-07-05',
            'tgl_terima' => '2023-07-06',
            'acara' => 'Acara 2',
            'tanggalBerangkat' => '2023-07-07',
            'tanggalPulang' => '2023-07-08',
            'jamMulai' => '10:00:00',
            'tempat' => 'Tempat 2',
            'perihal' => 'Perihal 2',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'jenis_agenda_tp' => 'Agenda C',
            'kode_lama' => Str::random(10),
            'kode_baru' => Str::random(10),
            'nomor_surat' => '125/ABC/2023',
            'opd_id' => 'OPD003',
            'tgl_surat' => '2023-07-09',
            'tgl_terima' => '2023-07-10',
            'acara' => 'Acara 3',
            'tanggalBerangkat' => '2023-07-11',
            'tanggalPulang' => '2023-07-12',
            'jamMulai' => '11:00:00',
            'tempat' => 'Tempat 3',
            'perihal' => 'Perihal 3',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'jenis_agenda_tp' => 'Agenda D',
            'kode_lama' => Str::random(10),
            'kode_baru' => Str::random(10),
            'nomor_surat' => '126/ABC/2023',
            'opd_id' => 'OPD004',
            'tgl_surat' => '2023-07-13',
            'tgl_terima' => '2023-07-14',
            'acara' => 'Acara 4',
            'tanggalBerangkat' => '2023-07-15',
            'tanggalPulang' => '2023-07-16',
            'jamMulai' => '12:00:00',
            'tempat' => 'Tempat 4',
            'perihal' => 'Perihal 4',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'jenis_agenda_tp' => 'Agenda E',
            'kode_lama' => Str::random(10),
            'kode_baru' => Str::random(10),
            'nomor_surat' => '127/ABC/2023',
            'opd_id' => 'OPD005',
            'tgl_surat' => '2023-07-17',
            'tgl_terima' => '2023-07-18',
            'acara' => 'Acara 5',
            'tanggalBerangkat' => '2023-07-19',
            'tanggalPulang' => '2023-07-20',
            'jamMulai' => '13:00:00',
            'tempat' => 'Tempat 5',
            'perihal' => 'Perihal 5',
            'created_at' => now(),
            'updated_at' => now(),
        ],


        [
            'jenis_agenda_tp' => 'Agenda A',
            'kode_lama' => Str::random(10),
            'kode_baru' => Str::random(10),
            'nomor_surat' => '123/ABC/2023',
            'opd_id' => 'OPD001',
            'tgl_surat' => '2023-07-01',
            'tgl_terima' => '2023-07-02',
            'acara' => 'Acara 1',
            'tanggalBerangkat' => '2023-07-03',
            'tanggalPulang' => '2023-07-04',
            'jamMulai' => '09:00:00',
            'tempat' => 'Tempat 1',
            'perihal' => 'Perihal 1',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'jenis_agenda_tp' => 'Agenda B',
            'kode_lama' => Str::random(10),
            'kode_baru' => Str::random(10),
            'nomor_surat' => '124/ABC/2023',
            'opd_id' => 'OPD002',
            'tgl_surat' => '2023-07-05',
            'tgl_terima' => '2023-07-06',
            'acara' => 'Acara 2',
            'tanggalBerangkat' => '2023-07-07',
            'tanggalPulang' => '2023-07-08',
            'jamMulai' => '10:00:00',
            'tempat' => 'Tempat 2',
            'perihal' => 'Perihal 2',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'jenis_agenda_tp' => 'Agenda C',
            'kode_lama' => Str::random(10),
            'kode_baru' => Str::random(10),
            'nomor_surat' => '125/ABC/2023',
            'opd_id' => 'OPD003',
            'tgl_surat' => '2023-07-09',
            'tgl_terima' => '2023-07-10',
            'acara' => 'Acara 3',
            'tanggalBerangkat' => '2023-07-11',
            'tanggalPulang' => '2023-07-12',
            'jamMulai' => '11:00:00',
            'tempat' => 'Tempat 3',
            'perihal' => 'Perihal 3',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'jenis_agenda_tp' => 'Agenda D',
            'kode_lama' => Str::random(10),
            'kode_baru' => Str::random(10),
            'nomor_surat' => '126/ABC/2023',
            'opd_id' => 'OPD004',
            'tgl_surat' => '2023-07-13',
            'tgl_terima' => '2023-07-14',
            'acara' => 'Acara 4',
            'tanggalBerangkat' => '2023-07-15',
            'tanggalPulang' => '2023-07-16',
            'jamMulai' => '12:00:00',
            'tempat' => 'Tempat 4',
            'perihal' => 'Perihal 4',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'jenis_agenda_tp' => 'Agenda E',
            'kode_lama' => Str::random(10),
            'kode_baru' => Str::random(10),
            'nomor_surat' => '127/ABC/2023',
            'opd_id' => 'OPD005',
            'tgl_surat' => '2023-07-17',
            'tgl_terima' => '2023-07-18',
            'acara' => 'Acara 5',
            'tanggalBerangkat' => '2023-07-19',
            'tanggalPulang' => '2023-07-20',
            'jamMulai' => '13:00:00',
            'tempat' => 'Tempat 5',
            'perihal' => 'Perihal 5',
            'created_at' => now(),
            'updated_at' => now(),
        ],
    ];

    // Masukkan data ke dalam tabel menggunakan DB::insert
    DB::table('surat_masuks')->insert($data);
}
}
