<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class SuratKeluarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $data = [
            [
                'nomor_surat' => 'SK-001',
                // 'jenis_surat' => 'surat_undangan',
                'tanggal_surat' => '2024-07-01',
                'perihal' => 'Pemberitahuan Karyawan Baru',
                'tujuan' => 'Semua Karyawan',
                'pembukaan' => 'Dengan ini kami sampaikan...',
                'isi' => 'Sehubungan dengan kebutuhan perusahaan...',
                'penutup' => 'Demikian surat ini kami sampaikan...',
                // 'lampiran' => 'CV dan foto karyawan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_surat' => 'SK-002',
                // 'jenis_surat' => 'Surat Pemberitahuan',
                'tanggal_surat' => '2024-07-02',
                'perihal' => 'Undangan Rapat Koordinasi',
                'tujuan' => 'Manajemen',
                'pembukaan_surat' => 'Kami mengundang Anda untuk hadir...',
                'isi_surat' => 'Pada hari yang telah ditentukan...',
                'penutup_surat' => 'Harap konfirmasi kehadiran Anda...',
                // 'lampiran' => 'Agenda rapat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_surat' => 'SK-001',
                // 'jenis_surat' => 'surat_undangan',
                'tanggal_surat' => '2024-07-01',
                'perihal' => 'Pemberitahuan Karyawan Baru',
                'tujuan' => 'Semua Karyawan',
                'pembukaan_surat' => 'Dengan ini kami sampaikan...',
                'isi_surat' => 'Sehubungan dengan kebutuhan perusahaan...',
                'penutup_surat' => 'Demikian surat ini kami sampaikan...',
                // 'lampiran' => 'CV dan foto karyawan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_surat' => 'SK-002',
                // 'jenis_surat' => 'Surat Pemberitahuan',
                'tanggal_surat' => '2024-07-02',
                'perihal' => 'Undangan Rapat Koordinasi',
                'tujuan' => 'Manajemen',
                'pembukaan_surat' => 'Kami mengundang Anda untuk hadir...',
                'isi_surat' => 'Pada hari yang telah ditentukan...',
                'penutup_surat' => 'Harap konfirmasi kehadiran Anda...',
                // 'lampiran' => 'Agenda rapat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_surat' => 'SK-001',
                // 'jenis_surat' => 'surat_undangan',
                'tanggal_surat' => '2024-07-01',
                'perihal' => 'Pemberitahuan Karyawan Baru',
                'tujuan' => 'Semua Karyawan',
                'pembukaan_surat' => 'Dengan ini kami sampaikan...',
                'isi_surat' => 'Sehubungan dengan kebutuhan perusahaan...',
                'penutup_surat' => 'Demikian surat ini kami sampaikan...',
                // 'lampiran' => 'CV dan foto karyawan',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'nomor_surat' => 'SK-001',
                // 'jenis_surat' => 'surat_undangan',
                'tanggal_surat' => '2024-07-01',
                'perihal' => 'Pemberitahuan Karyawan Baru',
                'tujuan' => 'Semua Karyawan',
                'pembukaan_surat' => 'Dengan ini kami sampaikan...',
                'isi_surat' => 'Sehubungan dengan kebutuhan perusahaan...',
                'penutup_surat' => 'Demikian surat ini kami sampaikan...',
                // 'lampiran' => 'CV dan foto karyawan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_surat' => 'SK-002',
                // 'jenis_surat' => 'Surat Pemberitahuan',
                'tanggal_surat' => '2024-07-02',
                'perihal' => 'Undangan Rapat Koordinasi',
                'tujuan' => 'Manajemen',
                'pembukaan_surat' => 'Kami mengundang Anda untuk hadir...',
                'isi_surat' => 'Pada hari yang telah ditentukan...',
                'penutup_surat' => 'Harap konfirmasi kehadiran Anda...',
                // 'lampiran' => 'Agenda rapat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_surat' => 'SK-001',
                // 'jenis_surat' => 'surat_undangan',
                'tanggal_surat' => '2024-07-01',
                'perihal' => 'Pemberitahuan Karyawan Baru',
                'tujuan' => 'Semua Karyawan',
                'pembukaan_surat' => 'Dengan ini kami sampaikan...',
                'isi_surat' => 'Sehubungan dengan kebutuhan perusahaan...',
                'penutup_surat' => 'Demikian surat ini kami sampaikan...',
                // 'lampiran' => 'CV dan foto karyawan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_surat' => 'SK-002',
                // 'jenis_surat' => 'Surat Pemberitahuan',
                'tanggal_surat' => '2024-07-02',
                'perihal' => 'Undangan Rapat Koordinasi',
                'tujuan' => 'Manajemen',
                'pembukaan_surat' => 'Kami mengundang Anda untuk hadir...',
                'isi_surat' => 'Pada hari yang telah ditentukan...',
                'penutup_surat' => 'Harap konfirmasi kehadiran Anda...',
                // 'lampiran' => 'Agenda rapat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_surat' => 'SK-001',
                // 'jenis_surat' => 'surat_undangan',
                'tanggal_surat' => '2024-07-01',
                'perihal' => 'Pemberitahuan Karyawan Baru',
                'tujuan' => 'Semua Karyawan',
                'pembukaan_surat' => 'Dengan ini kami sampaikan...',
                'isi_surat' => 'Sehubungan dengan kebutuhan perusahaan...',
                'penutup_surat' => 'Demikian surat ini kami sampaikan...',
                // 'lampiran' => 'CV dan foto karyawan',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'nomor_surat' => 'SK-001',
                // 'jenis_surat' => 'surat_undangan',
                'tanggal_surat' => '2024-07-01',
                'perihal' => 'Pemberitahuan Karyawan Baru',
                'tujuan' => 'Semua Karyawan',
                'pembukaan_surat' => 'Dengan ini kami sampaikan...',
                'isi_surat' => 'Sehubungan dengan kebutuhan perusahaan...',
                'penutup_surat' => 'Demikian surat ini kami sampaikan...',
                // 'lampiran' => 'CV dan foto karyawan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_surat' => 'SK-002',
                // 'jenis_surat' => 'Surat Pemberitahuan',
                'tanggal_surat' => '2024-07-02',
                'perihal' => 'Undangan Rapat Koordinasi',
                'tujuan' => 'Manajemen',
                'pembukaan_surat' => 'Kami mengundang Anda untuk hadir...',
                'isi_surat' => 'Pada hari yang telah ditentukan...',
                'penutup_surat' => 'Harap konfirmasi kehadiran Anda...',
                // 'lampiran' => 'Agenda rapat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_surat' => 'SK-001',
                // 'jenis_surat' => 'surat_undangan',
                'tanggal_surat' => '2024-07-01',
                'perihal' => 'Pemberitahuan Karyawan Baru',
                'tujuan' => 'Semua Karyawan',
                'pembukaan_surat' => 'Dengan ini kami sampaikan...',
                'isi_surat' => 'Sehubungan dengan kebutuhan perusahaan...',
                'penutup_surat' => 'Demikian surat ini kami sampaikan...',
                // 'lampiran' => 'CV dan foto karyawan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_surat' => 'SK-002',
                // 'jenis_surat' => 'Surat Pemberitahuan',
                'tanggal_surat' => '2024-07-02',
                'perihal' => 'Undangan Rapat Koordinasi',
                'tujuan' => 'Manajemen',
                'pembukaan_surat' => 'Kami mengundang Anda untuk hadir...',
                'isi_surat' => 'Pada hari yang telah ditentukan...',
                'penutup_surat' => 'Harap konfirmasi kehadiran Anda...',
                // 'lampiran' => 'Agenda rapat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_surat' => 'SK-001',
                // 'jenis_surat' => 'surat_undangan',
                'tanggal_surat' => '2024-07-01',
                'perihal' => 'Pemberitahuan Karyawan Baru',
                'tujuan' => 'Semua Karyawan',
                'pembukaan_surat' => 'Dengan ini kami sampaikan...',
                'isi_surat' => 'Sehubungan dengan kebutuhan perusahaan...',
                'penutup_surat' => 'Demikian surat ini kami sampaikan...',
                // 'lampiran' => 'CV dan foto karyawan',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nomor_surat' => 'SK-001',
                // 'jenis_surat' => 'surat_undangan',
                'tanggal_surat' => '2024-07-01',
                'perihal' => 'Pemberitahuan Karyawan Baru',
                'tujuan' => 'Semua Karyawan',
                'pembukaan_surat' => 'Dengan ini kami sampaikan...',
                'isi_surat' => 'Sehubungan dengan kebutuhan perusahaan...',
                'penutup_surat' => 'Demikian surat ini kami sampaikan...',
                // 'lampiran' => 'CV dan foto karyawan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_surat' => 'SK-001',
                // 'jenis_surat' => 'surat_undangan',
                'tanggal_surat' => '2024-07-01',
                'perihal' => 'Pemberitahuan Karyawan Baru',
                'tujuan' => 'Semua Karyawan',
                'pembukaan_surat' => 'Dengan ini kami sampaikan...',
                'isi_surat' => 'Sehubungan dengan kebutuhan perusahaan...',
                'penutup_surat' => 'Demikian surat ini kami sampaikan...',
                // 'lampiran' => 'CV dan foto karyawan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_surat' => 'SK-001',
                // 'jenis_surat' => 'surat_undangan',
                'tanggal_surat' => '2024-07-01',
                'perihal' => 'Pemberitahuan Karyawan Baru',
                'tujuan' => 'Semua Karyawan',
                'pembukaan_surat' => 'Dengan ini kami sampaikan...',
                'isi_surat' => 'Sehubungan dengan kebutuhan perusahaan...',
                'penutup_surat' => 'Demikian surat ini kami sampaikan...',
                // 'lampiran' => 'CV dan foto karyawan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_surat' => 'SK-001',
                // 'jenis_surat' => 'surat_undangan',
                'tanggal_surat' => '2024-07-01',
                'perihal' => 'Pemberitahuan Karyawan Baru',
                'tujuan' => 'Semua Karyawan',
                'pembukaan_surat' => 'Dengan ini kami sampaikan...',
                'isi_surat' => 'Sehubungan dengan kebutuhan perusahaan...',
                'penutup_surat' => 'Demikian surat ini kami sampaikan...',
                // 'lampiran' => 'CV dan foto karyawan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_surat' => 'SK-001',
                // 'jenis_surat' => 'surat_undangan',
                'tanggal_surat' => '2024-07-01',
                'perihal' => 'Pemberitahuan Karyawan Baru',
                'tujuan' => 'Semua Karyawan',
                'pembukaan_surat' => 'Dengan ini kami sampaikan...',
                'isi_surat' => 'Sehubungan dengan kebutuhan perusahaan...',
                'penutup_surat' => 'Demikian surat ini kami sampaikan...',
                // 'lampiran' => 'CV dan foto karyawan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Masukkan data ke dalam tabel menggunakan Query Builder
        DB::table('surat_keluars')->insert($data);
    }
}
