<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class TindakLanjutSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'surat_masuk_id' => 6,
                'surat_keluar_id' => null,
                // 'nip' => '197108251999031006',
                // 'nama' => 'John Doe',
                'deskripsi' => 'Lakukan tindakan A',
                'diteruskan_kepada' => 'Bidang Informatika',
                // 'disposisi' => 'Disposisi 1',
                'revisi' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'surat_masuk_id' => 7,
                'surat_keluar_id' => null,
                // 'nip' => '197108251999031006',
                // 'nama' => 'John Doe',
                'deskripsi' => 'Lakukan tindakan B',
                'diteruskan_kepada' => 'Bidang Informatika',
                // 'disposisi' => 'Disposisi 1',
                'revisi' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'surat_masuk_id' => 8,
                'surat_keluar_id' => null,
                // 'nip' => '197108251999031006',
                // 'nama' => 'John Doe',
                'deskripsi' => 'Lakukan tindakan A',
                'diteruskan_kepada' => 'Bidang Informatika',
                // 'disposisi' => 'Disposisi 1',
                'revisi' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'surat_masuk_id' => 9,
                'surat_keluar_id' => null,
                // 'nip' => '197108251999031006',
                // 'nama' => 'John Doe',
                'deskripsi' => 'Lakukan tindakan B',
                'diteruskan_kepada' => 'Bidang Informatika',
                // 'disposisi' => 'Disposisi 1',
                'revisi' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'surat_masuk_id' => 10,
                'surat_keluar_id' => null,
                // 'nip' => '197108251999031006',
                // 'nama' => 'John Doe',
                'deskripsi' => 'Lakukan tindakan A',
                'diteruskan_kepada' => 'Bidang Informatika',
                // 'disposisi' => 'Disposisi 1',
                'revisi' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'surat_masuk_id' => 11,
                'surat_keluar_id' => null,
                // 'nip' => '197108251999031006',
                // 'nama' => 'John Doe',
                'deskripsi' => 'Lakukan tindakan A',
                'diteruskan_kepada' => 'Bidang Informatika',
                // 'disposisi' => 'Disposisi 1',
                'revisi' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'surat_masuk_id' => 12,
                'surat_keluar_id' => null,
                // 'nip' => '197108251999031006',
                // 'nama' => 'John Doe',
                'deskripsi' => 'Lakukan tindakan A',
                'diteruskan_kepada' => 'Bidang Informatika',
                // 'disposisi' => 'Disposisi 1',
                'revisi' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'surat_masuk_id' => 13,
                'surat_keluar_id' => null,
                // 'nip' => '197108251999031006',
                // 'nama' => 'John Doe',
                'deskripsi' => 'Lakukan tindakan A',
                'diteruskan_kepada' => 'Bidang Informatika',
                // 'disposisi' => 'Disposisi 1',
                'revisi' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'surat_masuk_id' => 14,
                'surat_keluar_id' => null,
                // 'nip' => '197108251999031006',
                // 'nama' => 'John Doe',
                'deskripsi' => 'Revisi A',
                'diteruskan_kepada' => 'Bidang Informatika',
                // 'disposisi' => 'Disposisi 1',
                'revisi' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'surat_masuk_id' => 15,
                'surat_keluar_id' => null,
                // 'nip' => '197108251999031006',
                // 'nama' => 'John Doe',
                'deskripsi' => 'Revisi A',
                'diteruskan_kepada' => 'Bidang Informatika',
                // 'disposisi' => 'Disposisi 1',
                'revisi' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'surat_masuk_id' => 16,
                'surat_keluar_id' => null,
                // 'nip' => '197108251999031006',
                // 'nama' => 'John Doe',
                'deskripsi' => 'Revisi A',
                'diteruskan_kepada' => 'Bidang Informatika',
                // 'disposisi' => ' SETO RITMA RUMEKSO S.Kom. - Bidang Informatika',
                'revisi' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'surat_masuk_id' => 17,
                'surat_keluar_id' => null,
                // 'nip' => '197108251999031006',
                // 'nama' => 'John Doe',
                'deskripsi' => 'Revisi B',
                'diteruskan_kepada' => 'Bidang Informatika',
                // 'disposisi' => ' SADDAM HUSAIN S.Kom. - Bidang Informatika',
                'revisi' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'surat_masuk_id' => 18,
                'surat_keluar_id' => null,
                // 'nip' => '197108251999031006',
                // 'nama' => 'John Doe',
                'deskripsi' => 'Lakukan tindakan A',
                'diteruskan_kepada' => 'Bidang Informatika',
                // 'disposisi' => 'Disposisi 1',
                'revisi' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'surat_masuk_id' => 19,
                'surat_keluar_id' => null,
                // 'nip' => '197108251999031006',
                // 'nama' => 'John Doe',
                'deskripsi' => 'Lakukan tindakan B',
                'diteruskan_kepada' => 'Bidang Informatika',
                // 'disposisi' => 'Disposisi 1',
                'revisi' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'surat_masuk_id' => 20,
                'surat_keluar_id' => null,
                // 'nip' => '197108251999031006',
                // 'nama' => 'John Doe',
                'deskripsi' => 'Lakukan tindakan A',
                'diteruskan_kepada' => 'Bidang Informatika',
                // 'disposisi' => 'Disposisi 1',
                'revisi' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],


            // [
            //     'surat_keluar_id' => 6,
            //     'surat_masuk_id' => null,
            //     // 'nip' => '197108251999031006',
            //     // 'nama' => 'John Doe',
            //     'deskripsi' => 'Lakukan tindakan A',
            //     // 'diteruskan_kepada' => 'Kepala D',
            //     // 'disposisi' => 'Disposisi 1',
            //     'revisi' => false,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'surat_keluar_id' => 7,
            //     'surat_masuk_id' => null,
            //     // 'nip' => '197108251999031006',
            //     // 'nama' => 'John Doe',
            //     'deskripsi' => 'Lakukan tindakan A',
            //     // 'diteruskan_kepada' => 'Kepala D',
            //     // 'disposisi' => 'Disposisi 1',
            //     'revisi' => false,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'surat_keluar_id' => 8,
            //     'surat_masuk_id' => null,
            //     // 'nip' => '197108251999031006',
            //     // 'nama' => 'John Doe',
            //     'deskripsi' => 'Lakukan tindakan A',
            //     // 'diteruskan_kepada' => 'Kepala D',
            //     // 'disposisi' => 'Disposisi 1',
            //     'revisi' => false,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'surat_keluar_id' => 9,
            //     'surat_masuk_id' => null,
            //     // 'nip' => '197108251999031006',
            //     // 'nama' => 'John Doe',
            //     'deskripsi' => 'Lakukan tindakan A',
            //     // 'diteruskan_kepada' => 'Kepala D',
            //     // 'disposisi' => 'Disposisi 1',
            //     'revisi' => false,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'surat_keluar_id' => 10,
            //     'surat_masuk_id' => null,
            //     // 'nip' => '197108251999031006',
            //     // 'nama' => 'John Doe',
            //     'deskripsi' => 'Lakukan tindakan A',
            //     // 'diteruskan_kepada' => 'Kepala D',
            //     // 'disposisi' => 'Disposisi 1',
            //     'revisi' => false,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],


            // [
            //     'surat_keluar_id' => 11,
            //     'surat_masuk_id' => null,
            //     // 'nip' => '197108251999031006',
            //     // 'nama' => 'John Doe',
            //     'deskripsi' => 'Lakukan tindakan A',
            //     // 'diteruskan_kepada' => 'Kepala D',
            //     // 'disposisi' => 'Disposisi 1',
            //     'revisi' => false,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'surat_keluar_id' => 12,
            //     'surat_masuk_id' => null,
            //     // 'nip' => '197108251999031006',
            //     // 'nama' => 'John Doe',
            //     'deskripsi' => 'Lakukan tindakan A',
            //     // 'diteruskan_kepada' => 'Kepala D',
            //     // 'disposisi' => 'Disposisi 1',
            //     'revisi' => false,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'surat_keluar_id' => 13,
            //     'surat_masuk_id' => null,
            //     // 'nip' => '197108251999031006',
            //     // 'nama' => 'John Doe',
            //     'deskripsi' => 'Lakukan tindakan A',
            //     // 'diteruskan_kepada' => 'Kepala D',
            //     // 'disposisi' => 'Disposisi 1',
            //     'revisi' => false,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'surat_keluar_id' => 14,
            //     'surat_masuk_id' => null,
            //     // 'nip' => '197108251999031006',
            //     // 'nama' => 'John Doe',
            //     'deskripsi' => 'Lakukan tindakan A',
            //     // 'diteruskan_kepada' => 'Kepala D',
            //     // 'disposisi' => 'Disposisi 1',
            //     'revisi' => true,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'surat_keluar_id' => 15,
            //     'surat_masuk_id' => null,
            //     // 'nip' => '197108251999031006',
            //     // 'nama' => 'John Doe',
            //     'deskripsi' => 'Lakukan tindakan A',
            //     // 'diteruskan_kepada' => 'Kepala D',
            //     // 'disposisi' => 'Disposisi 1',
            //     'revisi' => true,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],


            // [
            //     'surat_keluar_id' => 16,
            //     'surat_masuk_id' => null,
            //     // 'nip' => '197108251999031006',
            //     // 'nama' => 'John Doe',
            //     'deskripsi' => 'Lakukan tindakan A',
            //     // 'diteruskan_kepada' => 'Kepala D',
            //     // 'disposisi' => 'Disposisi 1',
            //     'revisi' => false,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'surat_keluar_id' => 17,
            //     'surat_masuk_id' => null,
            //     // 'nip' => '197108251999031006',
            //     // 'nama' => 'John Doe',
            //     'deskripsi' => 'Lakukan tindakan A',
            //     // 'diteruskan_kepada' => 'Kepala D',
            //     // 'disposisi' => 'Disposisi 1',
            //     'revisi' => false,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'surat_keluar_id' => 18,
            //     'surat_masuk_id' => null,
            //     // 'nip' => '197108251999031006',
            //     // 'nama' => 'John Doe',
            //     'deskripsi' => 'Lakukan tindakan A',
            //     // 'diteruskan_kepada' => 'Kepala D',
            //     // 'disposisi' => 'Disposisi 1',
            //     'revisi' => false,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'surat_keluar_id' => 19,
            //     'surat_masuk_id' => null,
            //     // 'nip' => '197108251999031006',
            //     // 'nama' => 'John Doe',
            //     'deskripsi' => 'Lakukan tindakan A',
            //     // 'diteruskan_kepada' => 'Kepala D',
            //     // 'disposisi' => 'Disposisi 1',
            //     'revisi' => false,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'surat_keluar_id' => 20,
            //     'surat_masuk_id' => null,
            //     // 'nip' => '197108251999031006',
            //     // 'nama' => 'John Doe',
            //     'deskripsi' => 'Lakukan tindakan A',
            //     // 'diteruskan_kepada' => 'Kepala D',
            //     // 'disposisi' => 'Disposisi 1',
            //     'revisi' => false,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
        ];
        DB::table('tindak_lanjuts')->insert($data);
    }
}
